# Banco de tips de finanzas personales
# Puedes editar, agregar o quitar tips libremente. El bot rota uno por día.

TIPS = [
    "💰 Antes de gastar, decide cuánto vas a ahorrar. El ahorro no es lo que sobra, es lo primero que apartas.",
    "🛟 Ten un fondo de emergencia de al menos 3 meses de tus gastos básicos. Es tu colchón contra imprevistos.",
    "📉 Evita las deudas para gastos que se consumen rápido, como comida o ropa. Reserva el crédito para lo que dura o produce valor.",
    "⏳ Antes de comprar algo caro, espera 24 horas. Si al día siguiente sigues queriéndolo, cómpralo.",
    "📝 Registra todos tus gastos por un mes. No puedes controlar lo que no mides.",
    "🎯 Ten metas de ahorro con nombre y fecha. 'Ahorrar' sin propósito es fácil de abandonar.",
    "💳 Paga siempre el total de tu tarjeta de crédito, no solo el mínimo. Los intereses acumulados cuestan más de lo que crees.",
    "🤖 Automatiza tu ahorro: que se transfiera solo, el mismo día que te pagan.",
    "📊 No mezcles tus gastos fijos (arriendo, servicios) con tus gastos variables (ocio, antojos) en la misma cuenta.",
    "🔍 Compara precios antes de comprar algo grande. Cinco minutos de comparación pueden ahorrarte semanas de trabajo.",
    "🚫 Evita los préstamos 'gota a gota' o informales: los intereses reales suelen ser mucho más altos de lo que parecen.",
    "📌 Ten claro tu ingreso neto mensual real, no el que crees tener. Es la base de cualquier presupuesto.",
    "📂 Divide tu sueldo en categorías: necesidades, ahorro y gustos. Una guía común es 50/30/20.",
    "🔁 Revisa tus suscripciones cada 3 meses. Muchas veces pagamos por servicios que ya no usamos.",
    "⚠️ No pidas un crédito para pagar otro crédito. Eso solo aplaza el problema y lo hace más grande.",
    "📈 Aprende la diferencia entre gasto y inversión. El gasto se va, la inversión te regresa algo.",
    "🛡️ Antes de invertir, ten tu fondo de emergencia listo. Invertir sin colchón es jugar con riesgo doble.",
    "💼 No dependas de un solo ingreso si puedes evitarlo. Un segundo ingreso, aunque pequeño, da estabilidad.",
    "📋 Revisa tu historial crediticio al menos una vez al año. Es tu carta de presentación financiera.",
    "🛒 Evita comprar por impulso en redes sociales. Las ofertas 'por tiempo limitado' casi siempre vuelven.",
    "🚀 Si vas a endeudarte, que sea para algo que aumente tu capacidad de generar ingresos.",
    "🥇 Ahorra primero, gasta después. No al revés.",
    "🏠 Ten una meta clara de para qué es cada ahorro: emergencia, vivienda, negocio. El dinero sin destino se gasta más fácil.",
    "🧭 No compares tu progreso financiero con el de otros. Cada quien tiene un punto de partida distinto.",
    "🍳 Cocinar en casa casi siempre es más barato y más saludable que pedir domicilio constantemente.",
    "🧮 Antes de un préstamo, calcula la cuota mensual real, no solo la tasa de interés que te ofrecen.",
    "📑 Ten un presupuesto por escrito, aunque sea simple. Lo que no se planea, se improvisa.",
    "🙅 Aprende a decir 'no' a gastos sociales que no están en tu presupuesto. Tu bolsillo te lo va a agradecer.",
    "🐜 Revisa tus gastos hormiga: cafés, snacks, apps. Suman más de lo que parece al mes.",
    "📚 La educación financiera es la mejor inversión: entender cómo funciona el dinero te ahorra errores costosos.",
]
